openapi: 3.1.0
info:
  title: API Stellenbewertung
  description: API STellenbewertung - Internen Stellen werden bewertet
  version: 1.0.0
servers:
  - url: 'https://api-stellenbewertung.org'
  - url: 'http://dev/stage'
  - url: 'http://prod/production'
  - url: 'http://localhost:8080'
  - url: 'http://localhost:4010'
paths:
  /person:
    get:
      summary: Get Person by ID - Personal Data
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonDTO"
components:
  schemas:
    PersonDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 326
        vorname:
          type: string
          example: "Selma"
        nachname:
          type: string
          example: "Sahin"
        abteilungsID:
          type: string
          example: "IT321"
      required:
        - vorname
        - nachname
